AUDIO="example.flac"
PROTO_DIR="examples/protocols"
CTX1="examples/contexts/generic_audio.yaml"
CTX2="examples/contexts/synthetic_structures.yaml"
OUT_BASE="output/example"
python run_analysis.py "$AUDIO" --config "$PROTO_DIR/01_temporal.yaml"        --output "$OUT_BASE/01_temporal"
python run_analysis.py "$AUDIO" --config "$PROTO_DIR/02_spectral.yaml"        --output "$OUT_BASE/02_spectral"
python run_analysis.py "$AUDIO" --config "$PROTO_DIR/03_time_frequency.yaml"  --output "$OUT_BASE/03_time_frequency"
python run_analysis.py "$AUDIO" --config "$PROTO_DIR/04_modulation.yaml"      --output "$OUT_BASE/04_modulation"
python run_analysis.py "$AUDIO" --config "$PROTO_DIR/05_information.yaml"     --output "$OUT_BASE/05_information"
python run_analysis.py "$AUDIO" --config "$PROTO_DIR/06_inter_channel.yaml"   --output "$OUT_BASE/06_inter_channel"
python run_analysis.py "$AUDIO" --config "$PROTO_DIR/07_steganography.yaml"   --output "$OUT_BASE/07_steganography"
python run_analysis.py "$AUDIO" --config "$PROTO_DIR/08_meta_analysis.yaml"   --output "$OUT_BASE/08_meta_analysis"